# Generated by Django 5.2.8 on 2025-11-27 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(help_text='Enter Customer Name', max_length=100)),
                ('customer_number', models.IntegerField(help_text='Enter Customer Number')),
                ('customer_email', models.CharField(help_text='Enter Customer Email', max_length=100)),
            ],
        ),
    ]
